### PR TITLE
Correctly convert from intervals to framerate

### PR DESCRIPTION
**Pull request by Roughack**
This fixes V4L2 capture with my camera that uses FrameIntervalEnum::Discrete

FrameInterval is the inverse to fps so the numerator and denominator was switched.

Also had to flip the logic when checking if the new camera_format matches the configured one.

### CODE REVIEW

**Review by l1npengtul — APPROVED** [review]
LGTM

**Comment by l1npengtul** [comment]
Looks good, Ill admit I did this entirely on conjecture because I didnt have a camera with intervals...


Thank you for contributing!

**Comment by Roughack** [comment]
> Looks good, Ill admit I did this entirely on conjecture because I didnt have a camera with intervals...
> 
> Thank you for contributing!

I think that is the norm when you lack the hardware to test it on. :D
Thanks for this library and keep up the good work. :+1:

**Comment by l1npengtul** [comment]
Thank you! I expect to fully release 0.10 soon, once I iron out the kinks on AVFoundation and MSMF!

**Pull request merged**
